"""rename last mail date

Revision ID: 5482169c815b
Revises: 6c0c1261671a
Create Date: 2025-11-07 20:47:53.297320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5482169c815b'
down_revision = '6c0c1261671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('matched_mail_date', sa.Date(), nullable=True))
    op.drop_column('matches', 'last_mail_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('last_mail_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('matches', 'matched_mail_date')
    # ### end Alembic commands ###
