"""baseline

Revision ID: ba871d5d2dfc
Revises: 
Create Date: 2025-11-04 09:33:06.947322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba871d5d2dfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_matches_run_crm_sid', table_name='matches')
    op.drop_index('idx_matches_run_mail_sid', table_name='matches')
    op.drop_index('uq_match_one_mail_per_crm', table_name='matches')
    op.create_unique_constraint('uq_match_one_mail_per_crm', 'matches', ['run_id', 'crm_line_no'])
    op.drop_index('uq_match_pair', table_name='matches')
    op.create_unique_constraint('uq_match_pair', 'matches', ['run_id', 'crm_line_no', 'mail_line_no'])
    op.drop_column('matches', 'line_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('line_no', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_constraint('uq_match_pair', 'matches', type_='unique')
    op.create_index('uq_match_pair', 'matches', ['run_id', 'crm_line_no', 'mail_line_no'], unique=True)
    op.drop_constraint('uq_match_one_mail_per_crm', 'matches', type_='unique')
    op.create_index('uq_match_one_mail_per_crm', 'matches', ['run_id', 'crm_line_no'], unique=True)
    op.create_index('idx_matches_run_mail_sid', 'matches', ['run_id', 'mail_id'], unique=False)
    op.create_index('idx_matches_run_crm_sid', 'matches', ['run_id', 'crm_id'], unique=False)
    # ### end Alembic commands ###
