"""add KPI + series + tops tables

Revision ID: c72900118a42
Revises: ade8c0e1f67e
Create Date: 2025-11-02 19:21:19.840186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c72900118a42'
down_revision = 'ade8c0e1f67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_kpis',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_mail', sa.Integer(), nullable=False),
    sa.Column('unique_mail_addresses', sa.Integer(), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('match_rate', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('match_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('revenue_per_mailer', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('avg_ticket_per_match', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('median_days_to_convert', sa.Integer(), nullable=False),
    sa.Column('first_job_date', sa.Date(), nullable=True),
    sa.Column('last_job_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('idx_run_kpis_dates', 'run_kpis', ['first_job_date', 'last_job_date'], unique=False)
    op.create_index('idx_run_kpis_user', 'run_kpis', ['user_id'], unique=False)
    op.create_table('run_series',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('series', sa.String(length=32), nullable=False),
    sa.Column('ym', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_series_run', 'run_series', ['run_id'], unique=False)
    op.create_index('idx_run_series_unique', 'run_series', ['run_id', 'series', 'ym'], unique=True)
    op.create_table('run_top_cities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.Column('match_rate', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_top_cities_run', 'run_top_cities', ['run_id'], unique=False)
    op.create_table('run_top_zips',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('zip5', sa.String(length=5), nullable=False),
    sa.Column('matches', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_run_top_zips_run', 'run_top_zips', ['run_id'], unique=False)
    op.create_index('idx_run_top_zips_zip', 'run_top_zips', ['zip5'], unique=False)
    op.drop_index('idx_raw_mail_run', table_name='staging_raw_mail')
    op.drop_index('idx_raw_mail_run_row', table_name='staging_raw_mail')
    op.drop_table('staging_raw_mail')
    op.drop_index('idx_stg_crm_run', table_name='staging_crm')
    op.drop_index('ix_staging_crm_run_id_crm_id', table_name='staging_crm')
    op.drop_table('staging_crm')
    op.drop_index('idx_stg_mail_run', table_name='staging_mail')
    op.drop_index('ix_staging_mail_run_id_id', table_name='staging_mail')
    op.drop_table('staging_mail')
    op.drop_index('idx_raw_crm_run', table_name='staging_raw_crm')
    op.drop_index('idx_raw_crm_run_row', table_name='staging_raw_crm')
    op.drop_table('staging_raw_crm')
    op.add_column('geo_points', sa.Column('source', sa.String(), nullable=False))
    op.drop_index('idx_geo_run_kind', table_name='geo_points')
    op.create_index('idx_geo_run_kind', 'geo_points', ['run_id', 'source'], unique=False)
    op.drop_index('idx_geo_user_kind_date', table_name='geo_points')
    op.create_index('idx_geo_user_kind_date', 'geo_points', ['user_id', 'source', 'event_date'], unique=False)
    op.drop_column('geo_points', 'kind')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_points', sa.Column('kind', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index('idx_geo_user_kind_date', table_name='geo_points')
    op.create_index('idx_geo_user_kind_date', 'geo_points', ['user_id', 'kind', 'event_date'], unique=False)
    op.drop_index('idx_geo_run_kind', table_name='geo_points')
    op.create_index('idx_geo_run_kind', 'geo_points', ['run_id', 'kind'], unique=False)
    op.drop_column('geo_points', 'source')
    op.create_table('staging_raw_crm',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rownum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name='staging_raw_crm_run_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staging_raw_crm_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staging_raw_crm_pkey')
    )
    op.create_index('idx_raw_crm_run_row', 'staging_raw_crm', ['run_id', 'rownum'], unique=False)
    op.create_index('idx_raw_crm_run', 'staging_raw_crm', ['run_id'], unique=False)
    op.create_table('staging_mail',
    sa.Column('id', sa.TEXT(), server_default=sa.text("nextval('staging_mail_id_seq'::regclass)"), autoincrement=False, nullable=True),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('address1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sent_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('line_no', sa.BIGINT(), server_default=sa.text("nextval('staging_mail_line_no_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name='staging_mail_run_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staging_mail_user_id_fkey'),
    sa.PrimaryKeyConstraint('run_id', 'line_no', name='staging_mail_pkey')
    )
    op.create_index('ix_staging_mail_run_id_id', 'staging_mail', ['run_id', 'id'], unique=False)
    op.create_index('idx_stg_mail_run', 'staging_mail', ['run_id'], unique=False)
    op.create_table('staging_crm',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('crm_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address1', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address2', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('job_value', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('line_no', sa.BIGINT(), server_default=sa.text("nextval('staging_crm_line_no_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name='staging_crm_run_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staging_crm_user_id_fkey'),
    sa.PrimaryKeyConstraint('run_id', 'line_no', name='staging_crm_pkey')
    )
    op.create_index('ix_staging_crm_run_id_crm_id', 'staging_crm', ['run_id', 'crm_id'], unique=False)
    op.create_index('idx_stg_crm_run', 'staging_crm', ['run_id'], unique=False)
    op.create_table('staging_raw_mail',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('rownum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name='staging_raw_mail_run_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='staging_raw_mail_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staging_raw_mail_pkey')
    )
    op.create_index('idx_raw_mail_run_row', 'staging_raw_mail', ['run_id', 'rownum'], unique=False)
    op.create_index('idx_raw_mail_run', 'staging_raw_mail', ['run_id'], unique=False)
    op.drop_index('idx_run_top_zips_zip', table_name='run_top_zips')
    op.drop_index('idx_run_top_zips_run', table_name='run_top_zips')
    op.drop_table('run_top_zips')
    op.drop_index('idx_run_top_cities_run', table_name='run_top_cities')
    op.drop_table('run_top_cities')
    op.drop_index('idx_run_series_unique', table_name='run_series')
    op.drop_index('idx_run_series_run', table_name='run_series')
    op.drop_table('run_series')
    op.drop_index('idx_run_kpis_user', table_name='run_kpis')
    op.drop_index('idx_run_kpis_dates', table_name='run_kpis')
    op.drop_table('run_kpis')
    # ### end Alembic commands ###
