"""baseline schema (MVP)

Revision ID: e704aed01709
Revises: 
Create Date: 2025-11-01 09:00:54.482437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e704aed01709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('crm', sa.String(), nullable=True),
    sa.Column('mail_provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('step', sa.String(), nullable=True),
    sa.Column('pct', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('mail_count', sa.Integer(), nullable=True),
    sa.Column('crm_count', sa.Integer(), nullable=True),
    sa.Column('match_count', sa.Integer(), nullable=True),
    sa.Column('mail_ready', sa.Boolean(), nullable=False),
    sa.Column('crm_ready', sa.Boolean(), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_runs_started_at', 'runs', ['started_at'], unique=False)
    op.create_index('idx_runs_status', 'runs', ['status'], unique=False)
    op.create_index('idx_runs_user', 'runs', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('metered_item_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('idx_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('geo_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geo_run_kind', 'geo_points', ['run_id', 'kind'], unique=False)
    op.create_index('idx_geo_user_kind_date', 'geo_points', ['user_id', 'kind', 'event_date'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('crm_id', sa.String(), nullable=True),
    sa.Column('crm_job_date', sa.Date(), nullable=True),
    sa.Column('job_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('crm_city', sa.String(), nullable=True),
    sa.Column('crm_state', sa.String(length=2), nullable=True),
    sa.Column('crm_zip', sa.String(), nullable=True),
    sa.Column('matched_mail_full_address', sa.Text(), nullable=True),
    sa.Column('mail_dates_in_window', sa.Text(), nullable=True),
    sa.Column('mail_count_in_window', sa.Integer(), nullable=True),
    sa.Column('last_mail_date', sa.Date(), nullable=True),
    sa.Column('confidence_percent', sa.Integer(), nullable=True),
    sa.Column('match_notes', sa.Text(), nullable=True),
    sa.Column('zip5', sa.String(length=5), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_matches_run', 'matches', ['run_id'], unique=False)
    op.create_index('idx_matches_state', 'matches', ['state'], unique=False)
    op.create_index('idx_matches_user', 'matches', ['user_id'], unique=False)
    op.create_index('idx_matches_user_date', 'matches', ['user_id', 'crm_job_date'], unique=False)
    op.create_index('idx_matches_zip5', 'matches', ['zip5'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_matches_zip5', table_name='matches')
    op.drop_index('idx_matches_user_date', table_name='matches')
    op.drop_index('idx_matches_user', table_name='matches')
    op.drop_index('idx_matches_state', table_name='matches')
    op.drop_index('idx_matches_run', table_name='matches')
    op.drop_table('matches')
    op.drop_index('idx_geo_user_kind_date', table_name='geo_points')
    op.drop_index('idx_geo_run_kind', table_name='geo_points')
    op.drop_table('geo_points')
    op.drop_index('idx_subscriptions_user', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_runs_user', table_name='runs')
    op.drop_index('idx_runs_status', table_name='runs')
    op.drop_index('idx_runs_started_at', table_name='runs')
    op.drop_table('runs')
    op.drop_table('users')
    # ### end Alembic commands ###
